# Sample workflow for testing TRAIN workflow
name: Tests

on:
  # Runs on pushes targeting the default branch
  push:
    # If at least one path matches a pattern in the paths filter, the workflow runs
    paths:
      - 'translatome/**'
      - '!docs/**'
    branches: ['dev']

  pull_request:
    branches_ignore: []


jobs:
  # Test job
  test:
    runs-on: ubuntu-latest
    container: snakemake/snakemake:v7.12.0
    steps:
      - name: Install git-lfs
        run: |
          apt-get update && apt-get install git-lfs
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: packages_install
        run: |
          python -V
          snakemake --version
          conda --version
          pip install .
          pip install seaborn wget glob2 goatools==1.3.9 numpy==1.23.1
      - name: test
        run: |
          python3 -m pytest translatome/src --doctest-modules
